doctrine:
    orm:
        mappings:
            SyliusOrderCommentsPlugin:
                type: xml
                dir: Resources/config/doctrine/model
                prefix: 'Sylius\OrderCommentsPlugin\Domain\Model'
    dbal:
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType

sylius_resource:
    resources:
        sylius.order_comment:
            driver: doctrine/orm
            classes:
                model: Sylius\OrderCommentsPlugin\Domain\Model\Comment

doctrine_orm_bridge:
    entity_manager: default
    connection: default

sylius_mailer:
    emails:
        unread_comment:
            subject: sylius.emails.unread_comment.subject
            template: "SyliusOrderCommentsPlugin:Email:unread_comment.html.twig"
